[build]
  command = "node build.js"
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/data/**"]

[dev]
  port = 8080
  functionsPort = 3001
